version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Proyecto/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Proyecto/archivos:/app/archivos
      - ./Proyecto/outputs:/app/outputs
      - ./Proyecto/input:/app/input
    command: python3 /app/server.py

  frontend:
    build:
      context: ./FRONT-SQL
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend